import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UploadBox from "../components/UploadBox";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [showUpload, setShowUpload] = useState(true);
  const [preview, setPreview] = useState();
  const [gif, setGif] = useState(true);
  const [link, setLink] = useState("car.jpeg");

  const handelSubmit = () => {
    if (!selectedFile) {
      alert("Please Select an image");
      return;
    }
    setShowUpload(false);
    setPreview(undefined);
    setTimeout(() => {
      setGif(false);
    }, 2000);
  };

  useEffect(() => {
    // create the preview
    if (!selectedFile) {
      setPreview(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(selectedFile);
    setPreview(objectUrl);

    // free memory when ever this component is unmounted
    return () => URL.revokeObjectURL(objectUrl);
  }, [selectedFile]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl font-bold m-5 mt-14 font-sans p-1">
          Upload image
        </h1>

        <UploadBox
          selectedFile={selectedFile}
          setSelectedFile={setSelectedFile}
          showUpload={showUpload}
          link={link}
          preview={preview}
          gif={gif}
        />

        <button
          className="uploadButton w-48 rounded-lg py-3 px-6 cursor-pointer font-medium text-lg m-5 duration-300 bg-blue-600 text-white hover:tracking-wider"
          onClick={handelSubmit}
        >
          Submit
        </button>
      </main>
    </>
  );
}
